### ISSUE TITLE
Protos with imported dependencies cannot be loaded

### ISSUE THREAD

**Issue by twrobel3** [uw-labs/bloomrpc#102]
On a larger codebase of ours, we have protos split between multiple files.  In particular, the data model protos, which are shared amongst multiple parts of the system, are in a separate file from the service protos, and are imported.  Simplified example below:

`protos/exampleModel.proto`:
```proto
syntax = "proto3";
package protos;

message Value {
  string name = 1;
  string id = 2;
}
```

`protos/exampleService.proto`:
```proto
syntax = "proto3";
package protos;

import "protos/exampleModel.proto";

service ExampleService {
  rpc RunSearch (ExampleSearch) returns (SearchResponse) {}
}

message ExampleSearch {}

message SearchResponse {
  repeated Value items = 1;
}
```

These protos, placed in the same directly, compile fine with protoc, and the import is resolved.  However I'm unable to load service.proto into bloom.  Attempting to load the two together or loading the model before the service proto yields the same error: "no such Type or Enum 'Value' in Type .protos.SearchResponse"

**Comment by fenos** [comment]
@twrobel3 Hi there!

I've tried your example protos my self and i've got the same error.
Although i then noticed that you have something wrong in your `protos/exampleService.proto`.

If both of the protos lives within the same folder then your `import` should be  only `import "exampleModel.proto";` without the `protos` prefix`. If you try to load it like this it works.

The reason why your `protoc` works is because you probably have set an `import path`  resolution.

So if you don't want to change your import, you need to tell bloomrpc the same thing.

- Open the import path option on the sidebar
- Add the absolute path the to folder one step back to the `protos` folder. 
- Click add +
- Try importing again

**Comment by fenos** [comment]
Let me know if that solve your issue, for now closing

**Comment by tooolbox** [comment]
@fenos this solved my issue--thank you!

(Might want to put this in an FAQ or something.)

**Comment by sheralam** [comment]
** Add the absolute path the to folder one step back to the protos folder. thanks, @fenos. works as charm

**Comment by shrader** [comment]
Thanks @fenos. Leaving the import the same and adding the parent folder of proto to Bloom's _Import Paths_ worked for me also.
