### ISSUE TITLE
[Feature] refresh new load proto files

### ISSUE THREAD

**Issue by yangwenmai** [uw-labs/bloomrpc#119]
When I deleted all protos files, and reload these protos files.
The protos files also old protos file in tab.

**Comment by fenos** [comment]
This is done on purpose, because you might not want to loose the current state of your tabs when u reload the proto file from the file system.

Let me know if you have any some reasons on why we should close unexpectedly the tabs if you remove a protofile. 

Thanks for the feedback, i'm closing this for now. 
I'll re-open if you are willing to explain the reasons behind this request a bit more.

**Comment by yangwenmai** [comment]
OK, Thank you for your response.
But When I open many tabs proto files, It's bad to reload for every tab.

**Comment by telzul** [comment]
Greetings! I also stumbled across this today. I see your point that keeping the old state is useful. Maybe you could add some kind of notification on the tab that it is out of sync with the current proto definition.
Then it could create a new tab when clicking on the request in the sidebar - with the new proto loaded.
