### ISSUE TITLE
I suggest to create home brew formula for broomrpc

### ISSUE THREAD

**Issue by harobed** [uw-labs/bloomrpc#16]
Hi,

I suggest to create [home brew formula](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md) for `broomrpc`.

Best regards,
Stéphane

**Comment by macdaddyaz** [comment]
I [created a Cask today](https://github.com/Homebrew/homebrew-cask/pull/56886), and it's been merged. However, it will require manual updates to track BloomRPC releases. Defining a Tap within this repository would help mitigate that.

**Comment by fenos** [comment]
@macdaddyaz Thanks a lot for creating the PR and making available bloomrpc on `brew`! 

I'm not too certain on how to approach brew updates just yet.
Correct me if I'm wrong so that I'd be glad to help with the cask formula updates.

At every minor or major release, I can just update the version in [This line](https://github.com/Homebrew/homebrew-cask/pull/56886/files#diff-c73d701db0cd59dedcf74e2eb234483bR2)

Then as soon it get merged it will be available on brew.

Regarding the `Tap` i'd be glad if you can explain a bit more what's the utility of it and how to set it up!

Thanks again!

**Comment by macdaddyaz** [comment]
@fenos Yep, that's all that's needed to maintain the cask.

I mentioned a Tap, because you and your team could control it directly, rather than relying on the Homebrew Cask team to merge your pull request. It would be a separate repository that contains the formula for BloomRPC (I mistakenly said before that it would be in this repo).

Of course, it really comes down to whether you want the overhead of direct control, or are fine with just creating a separate pull request with every release.

If you decide to go the Tap route, [here is Homebrew's documentation](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md). Heroku's [Tap for their CLI](https://github.com/heroku/homebrew-brew) is a nice simple example.

**Comment by fenos** [comment]
@macdaddyaz You are my homebrew hero! 

Thanks a ton for taking the time of sharing this as well for the making the cask! 

I’ll be closing this and consider it resolved.
I’ll also give a think about the tap! 

Cheers!
