### ISSUE TITLE
Gathering proto-contracts from Reflection

### ISSUE THREAD

**Issue by supcry** [uw-labs/bloomrpc#187]
There is well-known infrastructure service as Reflection: https://github.com/grpc/grpc/blob/master/doc/server-reflection.md. We are using it to get actual proto-contracts from server-instance.

Please add support alternative way to load "Protos" not only from a file, but also directly from grpc-service address through Reflection if it exposed.

**Comment by slawo** [comment]
This would be greatly appreciated.

**Comment by seertenedos** [comment]
totally agree here.  It is the main reason i use Grpcox over BloomRPC.

**Comment by jackielii** [comment]
dup of #11

**Comment by jackielii** [comment]
gg

**Comment by seertenedos** [comment]
putting in a import path of http://localhost:5001 in release 1.5.2 did nto work. Is the fix in that relase? i assume you just need to put the server root in and then it uses the reflection API to find all the GRPC services offered. It still feels like it should be more like the open to me rather than an import paths but if it works then it does not matter.

A nice to have would be to support metadata specifically a JWT token as even our reflection API's are protected when deployed on cloudrun but for now i am testing it local.  Hopefully it can auto detect HTTPS as well based on url as you can't set that either on the import screen
