### ISSUE TITLE
add support for ByteString

### ISSUE THREAD

**Issue by dirklu** [uw-labs/bloomrpc#29]
Hi
Great to see this useful tools.
can you add support for ByteSring, thank you!!

**Comment by fenos** [comment]
@dirklu Hi! 
Thanks for opening this topic! 

The current implementation of GRPC in NodeJS represents bytes as `Buffers` as suggested in this issue https://github.com/grpc/grpc/issues/7586 and implemented accordantly. 

**Protobuf** convert `Buffer` data type in an array of bytes during marshalling of the JSON object to a proto message.

So natively this can be hard to achieve, for the reason that i'll need to traverse the JSON object you provide and understand what field is an actual `byteString` then convert it under the hood in an array of bytes (a Buffer essentially).

If you send an array of bytes from `BloomRPC` your server should be able to parse the message and convert it into a native supported `data type` in your language. 

ex: If your server side language support bytes as native type it should be converted to a byte, otherwise it will be converted in a `Buffer` in case your server is written in JS

What's the reason why you want to send byteString instead of bytesArray?

**Comment by fenos** [comment]
Closed for inactivity, will re open if discussions will be on going
