### ISSUE TITLE
Parsing error while importing proto 

### ISSUE THREAD

**Issue by guanw** [uw-labs/bloomrpc#78]
The proto I used is [sampling.proto](https://github.com/jaegertracing/jaeger/blob/master/model/proto/api_v2/sampling.proto)

There seems to be parsing error for this. Appreciate any help here!

**Comment by fenos** [comment]
@guanw thanks a lot for reporting the parsing error,

by the first look I think there maybe be an issue around the `double` keyword which is ignored and fails to import the proto.

I'll be looking at this asap and send out a fix (probably tomorrow)

**Comment by fenos** [comment]
@guanw Hi! 

I've had a look at this and apparently the issue is around the protobuf syntax for that protofile you linked.

I've successfully loaded the protofile from you provided in bloomrpc after i removed the `semicolons` on this lines: https://github.com/jaegertracing/jaeger/blob/master/model/proto/api_v2/sampling.proto#L38-L46

resulting in this:
```
option (grpc.gateway.protoc_gen_swagger.options.openapiv2_swagger) = {
  info: {
    version: "1.0"
  }
  external_docs: {
    url: "https://github.com/jaegertracing/jaeger"
    description: "Jaeger API"
  }
  schemes: HTTP
  schemes: HTTPS
};
```

I'm not entirely sure why `protobufjs` parser doesn't like that semicolon in that place but this is out of bloomrpc power. Let me know if this help
