### ISSUE TITLE
support for custom options

### ISSUE THREAD

**Issue by yrreddy0123** [uw-labs/bloomrpc#85]
Hi,  we have a proto with custom options as below 
```
extend google.protobuf.FileOptions {
     string sample = 51235;
     string demo = 512236;
}

option (sample) = "Sample Value";
option (demo) = "Demo Value";
```

When i try to import, i am facing issue as  **Error while importing protos illegal token 'option'** 
It would be nice if there's a way to work with these kind of protos's.

Note : I am able to generate stubs.

**Comment by fenos** [comment]
@yrreddy0123 Hi!

The **options** are definitely supported from the editor

Try to move the `options` definitions above the `extend` keyword; 

Since the `options` are generally defined before all the messages types / services definitions. Probably a rule of protobuf it self or maybe specific to `protobuf.js` parser not entirely sure but happy to learn about it.

**Comment by yrreddy0123** [comment]
Hi @fenos  
         Thanks for quick reply. Its working after placing options above the extend. :)
