### ISSUE TITLE
Trying to import google/type dependencies

### ISSUE THREAD

**Issue by talon55** [uw-labs/bloomrpc#97]
My service depends on `"google/api/annotations.proto"` and `"google/type/date.proto"`. I've got the files locally and have them registered via Import Paths:

![Screenshot 2019-07-09 14 43 44](https://user-images.githubusercontent.com/649666/60925376-58136a80-a258-11e9-85c8-2a3b840df979.png)

When I try to add my service's proto file, I still get a an error:

![Screenshot 2019-07-09 14 47 38](https://user-images.githubusercontent.com/649666/60925413-82652800-a258-11e9-84dc-d9315814e8f7.png)

What else do I need to do to make this work?

**Comment by fenos** [comment]
@talon55 Hi there!

I think you got almost there, the only problem i see is the `import` path it's not correct, let me explain you.

Since your proto file is depending on `"google/api/annotations.proto"` you will need to use an absolute base path that will match the rest of your import path.

**example:**

 if your dependant protos lives in: `Users/edm/google/api/annotations.proto` and your parent proto imports them like this `import "google/api/annotations.proto"`,

Then you'll need to add in the import path the first segment `Users/edm/` in this way once the base path you provided and import path matches to the proto file full path it will work.
